// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: static_layer_setting.proto

#ifndef PROTOBUF_INCLUDED_static_5flayer_5fsetting_2eproto
#define PROTOBUF_INCLUDED_static_5flayer_5fsetting_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_static_5flayer_5fsetting_2eproto 

namespace protobuf_static_5flayer_5fsetting_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_static_5flayer_5fsetting_2eproto
namespace roborts_costmap {
class ParaStaticLayer;
class ParaStaticLayerDefaultTypeInternal;
extern ParaStaticLayerDefaultTypeInternal _ParaStaticLayer_default_instance_;
}  // namespace roborts_costmap
namespace google {
namespace protobuf {
template<> ::roborts_costmap::ParaStaticLayer* Arena::CreateMaybeMessage<::roborts_costmap::ParaStaticLayer>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace roborts_costmap {

// ===================================================================

class ParaStaticLayer : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:roborts_costmap.ParaStaticLayer) */ {
 public:
  ParaStaticLayer();
  virtual ~ParaStaticLayer();

  ParaStaticLayer(const ParaStaticLayer& from);

  inline ParaStaticLayer& operator=(const ParaStaticLayer& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ParaStaticLayer(ParaStaticLayer&& from) noexcept
    : ParaStaticLayer() {
    *this = ::std::move(from);
  }

  inline ParaStaticLayer& operator=(ParaStaticLayer&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ParaStaticLayer& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ParaStaticLayer* internal_default_instance() {
    return reinterpret_cast<const ParaStaticLayer*>(
               &_ParaStaticLayer_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ParaStaticLayer* other);
  friend void swap(ParaStaticLayer& a, ParaStaticLayer& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ParaStaticLayer* New() const final {
    return CreateMaybeMessage<ParaStaticLayer>(NULL);
  }

  ParaStaticLayer* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ParaStaticLayer>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ParaStaticLayer& from);
  void MergeFrom(const ParaStaticLayer& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ParaStaticLayer* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string topic_name = 8;
  bool has_topic_name() const;
  void clear_topic_name();
  static const int kTopicNameFieldNumber = 8;
  const ::std::string& topic_name() const;
  void set_topic_name(const ::std::string& value);
  #if LANG_CXX11
  void set_topic_name(::std::string&& value);
  #endif
  void set_topic_name(const char* value);
  void set_topic_name(const char* value, size_t size);
  ::std::string* mutable_topic_name();
  ::std::string* release_topic_name();
  void set_allocated_topic_name(::std::string* topic_name);

  // required bool first_map_only = 1;
  bool has_first_map_only() const;
  void clear_first_map_only();
  static const int kFirstMapOnlyFieldNumber = 1;
  bool first_map_only() const;
  void set_first_map_only(bool value);

  // required bool subscribe_to_updates = 2;
  bool has_subscribe_to_updates() const;
  void clear_subscribe_to_updates();
  static const int kSubscribeToUpdatesFieldNumber = 2;
  bool subscribe_to_updates() const;
  void set_subscribe_to_updates(bool value);

  // required bool track_unknown_space = 3;
  bool has_track_unknown_space() const;
  void clear_track_unknown_space();
  static const int kTrackUnknownSpaceFieldNumber = 3;
  bool track_unknown_space() const;
  void set_track_unknown_space(bool value);

  // required bool use_maximum = 4;
  bool has_use_maximum() const;
  void clear_use_maximum();
  static const int kUseMaximumFieldNumber = 4;
  bool use_maximum() const;
  void set_use_maximum(bool value);

  // required int32 unknown_cost_value = 5;
  bool has_unknown_cost_value() const;
  void clear_unknown_cost_value();
  static const int kUnknownCostValueFieldNumber = 5;
  ::google::protobuf::int32 unknown_cost_value() const;
  void set_unknown_cost_value(::google::protobuf::int32 value);

  // required int32 lethal_threshold = 7;
  bool has_lethal_threshold() const;
  void clear_lethal_threshold();
  static const int kLethalThresholdFieldNumber = 7;
  ::google::protobuf::int32 lethal_threshold() const;
  void set_lethal_threshold(::google::protobuf::int32 value);

  // required bool trinary_map = 6;
  bool has_trinary_map() const;
  void clear_trinary_map();
  static const int kTrinaryMapFieldNumber = 6;
  bool trinary_map() const;
  void set_trinary_map(bool value);

  // required bool is_raw_rosmessage = 9;
  bool has_is_raw_rosmessage() const;
  void clear_is_raw_rosmessage();
  static const int kIsRawRosmessageFieldNumber = 9;
  bool is_raw_rosmessage() const;
  void set_is_raw_rosmessage(bool value);

  // required bool is_debug = 10;
  bool has_is_debug() const;
  void clear_is_debug();
  static const int kIsDebugFieldNumber = 10;
  bool is_debug() const;
  void set_is_debug(bool value);

  // required int32 bonus_radius = 11;
  bool has_bonus_radius() const;
  void clear_bonus_radius();
  static const int kBonusRadiusFieldNumber = 11;
  ::google::protobuf::int32 bonus_radius() const;
  void set_bonus_radius(::google::protobuf::int32 value);

  // required int32 yaw_mode = 12;
  bool has_yaw_mode() const;
  void clear_yaw_mode();
  static const int kYawModeFieldNumber = 12;
  ::google::protobuf::int32 yaw_mode() const;
  void set_yaw_mode(::google::protobuf::int32 value);

  // required double car_radius_x = 13;
  bool has_car_radius_x() const;
  void clear_car_radius_x();
  static const int kCarRadiusXFieldNumber = 13;
  double car_radius_x() const;
  void set_car_radius_x(double value);

  // required double car_radius_y = 14;
  bool has_car_radius_y() const;
  void clear_car_radius_y();
  static const int kCarRadiusYFieldNumber = 14;
  double car_radius_y() const;
  void set_car_radius_y(double value);

  // required double car_radius = 15;
  bool has_car_radius() const;
  void clear_car_radius();
  static const int kCarRadiusFieldNumber = 15;
  double car_radius() const;
  void set_car_radius(double value);

  // required int32 car_obs_val = 16;
  bool has_car_obs_val() const;
  void clear_car_obs_val();
  static const int kCarObsValFieldNumber = 16;
  ::google::protobuf::int32 car_obs_val() const;
  void set_car_obs_val(::google::protobuf::int32 value);

  // required int32 buff_obs_val = 17;
  bool has_buff_obs_val() const;
  void clear_buff_obs_val();
  static const int kBuffObsValFieldNumber = 17;
  ::google::protobuf::int32 buff_obs_val() const;
  void set_buff_obs_val(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:roborts_costmap.ParaStaticLayer)
 private:
  void set_has_first_map_only();
  void clear_has_first_map_only();
  void set_has_subscribe_to_updates();
  void clear_has_subscribe_to_updates();
  void set_has_track_unknown_space();
  void clear_has_track_unknown_space();
  void set_has_use_maximum();
  void clear_has_use_maximum();
  void set_has_unknown_cost_value();
  void clear_has_unknown_cost_value();
  void set_has_trinary_map();
  void clear_has_trinary_map();
  void set_has_lethal_threshold();
  void clear_has_lethal_threshold();
  void set_has_topic_name();
  void clear_has_topic_name();
  void set_has_is_raw_rosmessage();
  void clear_has_is_raw_rosmessage();
  void set_has_is_debug();
  void clear_has_is_debug();
  void set_has_bonus_radius();
  void clear_has_bonus_radius();
  void set_has_yaw_mode();
  void clear_has_yaw_mode();
  void set_has_car_radius_x();
  void clear_has_car_radius_x();
  void set_has_car_radius_y();
  void clear_has_car_radius_y();
  void set_has_car_radius();
  void clear_has_car_radius();
  void set_has_car_obs_val();
  void clear_has_car_obs_val();
  void set_has_buff_obs_val();
  void clear_has_buff_obs_val();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr topic_name_;
  bool first_map_only_;
  bool subscribe_to_updates_;
  bool track_unknown_space_;
  bool use_maximum_;
  ::google::protobuf::int32 unknown_cost_value_;
  ::google::protobuf::int32 lethal_threshold_;
  bool trinary_map_;
  bool is_raw_rosmessage_;
  bool is_debug_;
  ::google::protobuf::int32 bonus_radius_;
  ::google::protobuf::int32 yaw_mode_;
  double car_radius_x_;
  double car_radius_y_;
  double car_radius_;
  ::google::protobuf::int32 car_obs_val_;
  ::google::protobuf::int32 buff_obs_val_;
  friend struct ::protobuf_static_5flayer_5fsetting_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ParaStaticLayer

// required bool first_map_only = 1;
inline bool ParaStaticLayer::has_first_map_only() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ParaStaticLayer::set_has_first_map_only() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ParaStaticLayer::clear_has_first_map_only() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ParaStaticLayer::clear_first_map_only() {
  first_map_only_ = false;
  clear_has_first_map_only();
}
inline bool ParaStaticLayer::first_map_only() const {
  // @@protoc_insertion_point(field_get:roborts_costmap.ParaStaticLayer.first_map_only)
  return first_map_only_;
}
inline void ParaStaticLayer::set_first_map_only(bool value) {
  set_has_first_map_only();
  first_map_only_ = value;
  // @@protoc_insertion_point(field_set:roborts_costmap.ParaStaticLayer.first_map_only)
}

// required bool subscribe_to_updates = 2;
inline bool ParaStaticLayer::has_subscribe_to_updates() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ParaStaticLayer::set_has_subscribe_to_updates() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ParaStaticLayer::clear_has_subscribe_to_updates() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ParaStaticLayer::clear_subscribe_to_updates() {
  subscribe_to_updates_ = false;
  clear_has_subscribe_to_updates();
}
inline bool ParaStaticLayer::subscribe_to_updates() const {
  // @@protoc_insertion_point(field_get:roborts_costmap.ParaStaticLayer.subscribe_to_updates)
  return subscribe_to_updates_;
}
inline void ParaStaticLayer::set_subscribe_to_updates(bool value) {
  set_has_subscribe_to_updates();
  subscribe_to_updates_ = value;
  // @@protoc_insertion_point(field_set:roborts_costmap.ParaStaticLayer.subscribe_to_updates)
}

// required bool track_unknown_space = 3;
inline bool ParaStaticLayer::has_track_unknown_space() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ParaStaticLayer::set_has_track_unknown_space() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ParaStaticLayer::clear_has_track_unknown_space() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ParaStaticLayer::clear_track_unknown_space() {
  track_unknown_space_ = false;
  clear_has_track_unknown_space();
}
inline bool ParaStaticLayer::track_unknown_space() const {
  // @@protoc_insertion_point(field_get:roborts_costmap.ParaStaticLayer.track_unknown_space)
  return track_unknown_space_;
}
inline void ParaStaticLayer::set_track_unknown_space(bool value) {
  set_has_track_unknown_space();
  track_unknown_space_ = value;
  // @@protoc_insertion_point(field_set:roborts_costmap.ParaStaticLayer.track_unknown_space)
}

// required bool use_maximum = 4;
inline bool ParaStaticLayer::has_use_maximum() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void ParaStaticLayer::set_has_use_maximum() {
  _has_bits_[0] |= 0x00000010u;
}
inline void ParaStaticLayer::clear_has_use_maximum() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void ParaStaticLayer::clear_use_maximum() {
  use_maximum_ = false;
  clear_has_use_maximum();
}
inline bool ParaStaticLayer::use_maximum() const {
  // @@protoc_insertion_point(field_get:roborts_costmap.ParaStaticLayer.use_maximum)
  return use_maximum_;
}
inline void ParaStaticLayer::set_use_maximum(bool value) {
  set_has_use_maximum();
  use_maximum_ = value;
  // @@protoc_insertion_point(field_set:roborts_costmap.ParaStaticLayer.use_maximum)
}

// required int32 unknown_cost_value = 5;
inline bool ParaStaticLayer::has_unknown_cost_value() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void ParaStaticLayer::set_has_unknown_cost_value() {
  _has_bits_[0] |= 0x00000020u;
}
inline void ParaStaticLayer::clear_has_unknown_cost_value() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void ParaStaticLayer::clear_unknown_cost_value() {
  unknown_cost_value_ = 0;
  clear_has_unknown_cost_value();
}
inline ::google::protobuf::int32 ParaStaticLayer::unknown_cost_value() const {
  // @@protoc_insertion_point(field_get:roborts_costmap.ParaStaticLayer.unknown_cost_value)
  return unknown_cost_value_;
}
inline void ParaStaticLayer::set_unknown_cost_value(::google::protobuf::int32 value) {
  set_has_unknown_cost_value();
  unknown_cost_value_ = value;
  // @@protoc_insertion_point(field_set:roborts_costmap.ParaStaticLayer.unknown_cost_value)
}

// required bool trinary_map = 6;
inline bool ParaStaticLayer::has_trinary_map() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void ParaStaticLayer::set_has_trinary_map() {
  _has_bits_[0] |= 0x00000080u;
}
inline void ParaStaticLayer::clear_has_trinary_map() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void ParaStaticLayer::clear_trinary_map() {
  trinary_map_ = false;
  clear_has_trinary_map();
}
inline bool ParaStaticLayer::trinary_map() const {
  // @@protoc_insertion_point(field_get:roborts_costmap.ParaStaticLayer.trinary_map)
  return trinary_map_;
}
inline void ParaStaticLayer::set_trinary_map(bool value) {
  set_has_trinary_map();
  trinary_map_ = value;
  // @@protoc_insertion_point(field_set:roborts_costmap.ParaStaticLayer.trinary_map)
}

// required int32 lethal_threshold = 7;
inline bool ParaStaticLayer::has_lethal_threshold() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void ParaStaticLayer::set_has_lethal_threshold() {
  _has_bits_[0] |= 0x00000040u;
}
inline void ParaStaticLayer::clear_has_lethal_threshold() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void ParaStaticLayer::clear_lethal_threshold() {
  lethal_threshold_ = 0;
  clear_has_lethal_threshold();
}
inline ::google::protobuf::int32 ParaStaticLayer::lethal_threshold() const {
  // @@protoc_insertion_point(field_get:roborts_costmap.ParaStaticLayer.lethal_threshold)
  return lethal_threshold_;
}
inline void ParaStaticLayer::set_lethal_threshold(::google::protobuf::int32 value) {
  set_has_lethal_threshold();
  lethal_threshold_ = value;
  // @@protoc_insertion_point(field_set:roborts_costmap.ParaStaticLayer.lethal_threshold)
}

// required string topic_name = 8;
inline bool ParaStaticLayer::has_topic_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ParaStaticLayer::set_has_topic_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ParaStaticLayer::clear_has_topic_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ParaStaticLayer::clear_topic_name() {
  topic_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_topic_name();
}
inline const ::std::string& ParaStaticLayer::topic_name() const {
  // @@protoc_insertion_point(field_get:roborts_costmap.ParaStaticLayer.topic_name)
  return topic_name_.GetNoArena();
}
inline void ParaStaticLayer::set_topic_name(const ::std::string& value) {
  set_has_topic_name();
  topic_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:roborts_costmap.ParaStaticLayer.topic_name)
}
#if LANG_CXX11
inline void ParaStaticLayer::set_topic_name(::std::string&& value) {
  set_has_topic_name();
  topic_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:roborts_costmap.ParaStaticLayer.topic_name)
}
#endif
inline void ParaStaticLayer::set_topic_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_topic_name();
  topic_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:roborts_costmap.ParaStaticLayer.topic_name)
}
inline void ParaStaticLayer::set_topic_name(const char* value, size_t size) {
  set_has_topic_name();
  topic_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:roborts_costmap.ParaStaticLayer.topic_name)
}
inline ::std::string* ParaStaticLayer::mutable_topic_name() {
  set_has_topic_name();
  // @@protoc_insertion_point(field_mutable:roborts_costmap.ParaStaticLayer.topic_name)
  return topic_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ParaStaticLayer::release_topic_name() {
  // @@protoc_insertion_point(field_release:roborts_costmap.ParaStaticLayer.topic_name)
  if (!has_topic_name()) {
    return NULL;
  }
  clear_has_topic_name();
  return topic_name_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ParaStaticLayer::set_allocated_topic_name(::std::string* topic_name) {
  if (topic_name != NULL) {
    set_has_topic_name();
  } else {
    clear_has_topic_name();
  }
  topic_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), topic_name);
  // @@protoc_insertion_point(field_set_allocated:roborts_costmap.ParaStaticLayer.topic_name)
}

// required bool is_raw_rosmessage = 9;
inline bool ParaStaticLayer::has_is_raw_rosmessage() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void ParaStaticLayer::set_has_is_raw_rosmessage() {
  _has_bits_[0] |= 0x00000100u;
}
inline void ParaStaticLayer::clear_has_is_raw_rosmessage() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void ParaStaticLayer::clear_is_raw_rosmessage() {
  is_raw_rosmessage_ = false;
  clear_has_is_raw_rosmessage();
}
inline bool ParaStaticLayer::is_raw_rosmessage() const {
  // @@protoc_insertion_point(field_get:roborts_costmap.ParaStaticLayer.is_raw_rosmessage)
  return is_raw_rosmessage_;
}
inline void ParaStaticLayer::set_is_raw_rosmessage(bool value) {
  set_has_is_raw_rosmessage();
  is_raw_rosmessage_ = value;
  // @@protoc_insertion_point(field_set:roborts_costmap.ParaStaticLayer.is_raw_rosmessage)
}

// required bool is_debug = 10;
inline bool ParaStaticLayer::has_is_debug() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void ParaStaticLayer::set_has_is_debug() {
  _has_bits_[0] |= 0x00000200u;
}
inline void ParaStaticLayer::clear_has_is_debug() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void ParaStaticLayer::clear_is_debug() {
  is_debug_ = false;
  clear_has_is_debug();
}
inline bool ParaStaticLayer::is_debug() const {
  // @@protoc_insertion_point(field_get:roborts_costmap.ParaStaticLayer.is_debug)
  return is_debug_;
}
inline void ParaStaticLayer::set_is_debug(bool value) {
  set_has_is_debug();
  is_debug_ = value;
  // @@protoc_insertion_point(field_set:roborts_costmap.ParaStaticLayer.is_debug)
}

// required int32 bonus_radius = 11;
inline bool ParaStaticLayer::has_bonus_radius() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void ParaStaticLayer::set_has_bonus_radius() {
  _has_bits_[0] |= 0x00000400u;
}
inline void ParaStaticLayer::clear_has_bonus_radius() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void ParaStaticLayer::clear_bonus_radius() {
  bonus_radius_ = 0;
  clear_has_bonus_radius();
}
inline ::google::protobuf::int32 ParaStaticLayer::bonus_radius() const {
  // @@protoc_insertion_point(field_get:roborts_costmap.ParaStaticLayer.bonus_radius)
  return bonus_radius_;
}
inline void ParaStaticLayer::set_bonus_radius(::google::protobuf::int32 value) {
  set_has_bonus_radius();
  bonus_radius_ = value;
  // @@protoc_insertion_point(field_set:roborts_costmap.ParaStaticLayer.bonus_radius)
}

// required int32 yaw_mode = 12;
inline bool ParaStaticLayer::has_yaw_mode() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void ParaStaticLayer::set_has_yaw_mode() {
  _has_bits_[0] |= 0x00000800u;
}
inline void ParaStaticLayer::clear_has_yaw_mode() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void ParaStaticLayer::clear_yaw_mode() {
  yaw_mode_ = 0;
  clear_has_yaw_mode();
}
inline ::google::protobuf::int32 ParaStaticLayer::yaw_mode() const {
  // @@protoc_insertion_point(field_get:roborts_costmap.ParaStaticLayer.yaw_mode)
  return yaw_mode_;
}
inline void ParaStaticLayer::set_yaw_mode(::google::protobuf::int32 value) {
  set_has_yaw_mode();
  yaw_mode_ = value;
  // @@protoc_insertion_point(field_set:roborts_costmap.ParaStaticLayer.yaw_mode)
}

// required double car_radius_x = 13;
inline bool ParaStaticLayer::has_car_radius_x() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
inline void ParaStaticLayer::set_has_car_radius_x() {
  _has_bits_[0] |= 0x00001000u;
}
inline void ParaStaticLayer::clear_has_car_radius_x() {
  _has_bits_[0] &= ~0x00001000u;
}
inline void ParaStaticLayer::clear_car_radius_x() {
  car_radius_x_ = 0;
  clear_has_car_radius_x();
}
inline double ParaStaticLayer::car_radius_x() const {
  // @@protoc_insertion_point(field_get:roborts_costmap.ParaStaticLayer.car_radius_x)
  return car_radius_x_;
}
inline void ParaStaticLayer::set_car_radius_x(double value) {
  set_has_car_radius_x();
  car_radius_x_ = value;
  // @@protoc_insertion_point(field_set:roborts_costmap.ParaStaticLayer.car_radius_x)
}

// required double car_radius_y = 14;
inline bool ParaStaticLayer::has_car_radius_y() const {
  return (_has_bits_[0] & 0x00002000u) != 0;
}
inline void ParaStaticLayer::set_has_car_radius_y() {
  _has_bits_[0] |= 0x00002000u;
}
inline void ParaStaticLayer::clear_has_car_radius_y() {
  _has_bits_[0] &= ~0x00002000u;
}
inline void ParaStaticLayer::clear_car_radius_y() {
  car_radius_y_ = 0;
  clear_has_car_radius_y();
}
inline double ParaStaticLayer::car_radius_y() const {
  // @@protoc_insertion_point(field_get:roborts_costmap.ParaStaticLayer.car_radius_y)
  return car_radius_y_;
}
inline void ParaStaticLayer::set_car_radius_y(double value) {
  set_has_car_radius_y();
  car_radius_y_ = value;
  // @@protoc_insertion_point(field_set:roborts_costmap.ParaStaticLayer.car_radius_y)
}

// required double car_radius = 15;
inline bool ParaStaticLayer::has_car_radius() const {
  return (_has_bits_[0] & 0x00004000u) != 0;
}
inline void ParaStaticLayer::set_has_car_radius() {
  _has_bits_[0] |= 0x00004000u;
}
inline void ParaStaticLayer::clear_has_car_radius() {
  _has_bits_[0] &= ~0x00004000u;
}
inline void ParaStaticLayer::clear_car_radius() {
  car_radius_ = 0;
  clear_has_car_radius();
}
inline double ParaStaticLayer::car_radius() const {
  // @@protoc_insertion_point(field_get:roborts_costmap.ParaStaticLayer.car_radius)
  return car_radius_;
}
inline void ParaStaticLayer::set_car_radius(double value) {
  set_has_car_radius();
  car_radius_ = value;
  // @@protoc_insertion_point(field_set:roborts_costmap.ParaStaticLayer.car_radius)
}

// required int32 car_obs_val = 16;
inline bool ParaStaticLayer::has_car_obs_val() const {
  return (_has_bits_[0] & 0x00008000u) != 0;
}
inline void ParaStaticLayer::set_has_car_obs_val() {
  _has_bits_[0] |= 0x00008000u;
}
inline void ParaStaticLayer::clear_has_car_obs_val() {
  _has_bits_[0] &= ~0x00008000u;
}
inline void ParaStaticLayer::clear_car_obs_val() {
  car_obs_val_ = 0;
  clear_has_car_obs_val();
}
inline ::google::protobuf::int32 ParaStaticLayer::car_obs_val() const {
  // @@protoc_insertion_point(field_get:roborts_costmap.ParaStaticLayer.car_obs_val)
  return car_obs_val_;
}
inline void ParaStaticLayer::set_car_obs_val(::google::protobuf::int32 value) {
  set_has_car_obs_val();
  car_obs_val_ = value;
  // @@protoc_insertion_point(field_set:roborts_costmap.ParaStaticLayer.car_obs_val)
}

// required int32 buff_obs_val = 17;
inline bool ParaStaticLayer::has_buff_obs_val() const {
  return (_has_bits_[0] & 0x00010000u) != 0;
}
inline void ParaStaticLayer::set_has_buff_obs_val() {
  _has_bits_[0] |= 0x00010000u;
}
inline void ParaStaticLayer::clear_has_buff_obs_val() {
  _has_bits_[0] &= ~0x00010000u;
}
inline void ParaStaticLayer::clear_buff_obs_val() {
  buff_obs_val_ = 0;
  clear_has_buff_obs_val();
}
inline ::google::protobuf::int32 ParaStaticLayer::buff_obs_val() const {
  // @@protoc_insertion_point(field_get:roborts_costmap.ParaStaticLayer.buff_obs_val)
  return buff_obs_val_;
}
inline void ParaStaticLayer::set_buff_obs_val(::google::protobuf::int32 value) {
  set_has_buff_obs_val();
  buff_obs_val_ = value;
  // @@protoc_insertion_point(field_set:roborts_costmap.ParaStaticLayer.buff_obs_val)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace roborts_costmap

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_static_5flayer_5fsetting_2eproto
